C:\Users\ASUS\Desktop\云计算\facial-recognition-attendance\.venv\Scripts\python.exe C:\Users\ASUS\Desktop\云计算\facial-recognition-attendance\backend\main.py FRS服务初始化失败: cannot import name 'FrsClientBuilder' from 'huaweicloudsdkfrs.v2' (C:\Users\ASUS\Desktop\云计算\facial-recognition-attendance\.venv\Lib\site-packages\huaweicloudsdkfrs\v2\__init__.py) FRS服务初始化失败: cannot import name 'FrsClientBuilder' from 'huaweicloudsdkfrs.v2' (C:\Users\ASUS\Desktop\云计算\facial-recognition-attendance\.venv\Lib\site-packages\huaweicloudsdkfrs\v2\__init__.py) INFO:     Started server process [8904] INFO:     Waiting for application startup. 2026-06-14 17:03:00.743 | INFO     | __main__:lifespan:29 - 应用启动中... 数据库初始化失败: (pymysql.err.OperationalError) (1045, "Access denied for user 'face_user'@'localhost' (using password: YES)") (Background on this error at: https://sqlalche.me/e/20/e3q8) 2026-06-14 17:03:00.768 | ERROR    | __main__:lifespan:35 - 应用启动失败: (pymysql.err.OperationalError) (1045, "Access denied for user 'face_user'@'localhost' (using password: YES)") (Background on this error at: https://sqlalche.me/e/20/e3q8) ERROR:    Traceback (most recent call last):   File "C:\Users\ASUS\Desktop\云计算\facial-recognition-attendance\.venv\Lib\site-packages\sqlalchemy\engine\base.py", line 144, in __init__     self._dbapi_connection = engine.raw_connection()                              ^^^^^^^^^^^^^^^^^^^^^^^   File "C:\Users\ASUS\Desktop\云计算\facial-recognition-attendance\.venv\Lib\site-packages\sqlalchemy\engine\base.py", line 3319, in raw_connection     return self.pool.connect()            ^^^^^^^^^^^^^^^^^^^   File "C:\Users\ASUS\Desktop\云计算\facial-recognition-attendance\.venv\Lib\site-packages\sqlalchemy\pool\base.py", line 448, in connect     return _ConnectionFairy._checkout(self)            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^   File "C:\Users\ASUS\Desktop\云计算\facial-recognition-attendance\.venv\Lib\site-packages\sqlalchemy\pool\base.py", line 1272, in _checkout     fairy = _ConnectionRecord.checkout(pool)             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^   File "C:\Users\ASUS\Desktop\云计算\facial-recognition-attendance\.venv\Lib\site-packages\sqlalchemy\pool\base.py", line 712, in checkout     rec = pool._do_get()           ^^^^^^^^^^^^^^   File "C:\Users\ASUS\Desktop\云计算\facial-recognition-attendance\.venv\Lib\site-packages\sqlalchemy\pool\impl.py", line 178, in _do_get     with util.safe_reraise():   File "C:\Users\ASUS\Desktop\云计算\facial-recognition-attendance\.venv\Lib\site-packages\sqlalchemy\util\langhelpers.py", line 122, in __exit__     raise exc_value.with_traceback(exc_tb)   File "C:\Users\ASUS\Desktop\云计算\facial-recognition-attendance\.venv\Lib\site-packages\sqlalchemy\pool\impl.py", line 176, in _do_get     return self._create_connection()            ^^^^^^^^^^^^^^^^^^^^^^^^^   File "C:\Users\ASUS\Desktop\云计算\facial-recognition-attendance\.venv\Lib\site-packages\sqlalchemy\pool\base.py", line 389, in _create_connection     return _ConnectionRecord(self)            ^^^^^^^^^^^^^^^^^^^^^^^   File "C:\Users\ASUS\Desktop\云计算\facial-recognition-attendance\.venv\Lib\site-packages\sqlalchemy\pool\base.py", line 674, in __init__     self.__connect()   File "C:\Users\ASUS\Desktop\云计算\facial-recognition-attendance\.venv\Lib\site-packages\sqlalchemy\pool\base.py", line 900, in __connect     with util.safe_reraise():   File "C:\Users\ASUS\Desktop\云计算\facial-recognition-attendance\.venv\Lib\site-packages\sqlalchemy\util\langhelpers.py", line 122, in __exit__     raise exc_value.with_traceback(exc_tb)   File "C:\Users\ASUS\Desktop\云计算\facial-recognition-attendance\.venv\Lib\site-packages\sqlalchemy\pool\base.py", line 896, in __connect     self.dbapi_connection = connection = pool._invoke_creator(self)                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^   File "C:\Users\ASUS\Desktop\云计算\facial-recognition-attendance\.venv\Lib\site-packages\sqlalchemy\engine\create.py", line 667, in connect     return dialect.connect(*cargs_tup, **cparams)            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^   File "C:\Users\ASUS\Desktop\云计算\facial-recognition-attendance\.venv\Lib\site-packages\sqlalchemy\engine\default.py", line 630, in connect     return self.loaded_dbapi.connect(*cargs, **cparams)  # type: ignore[no-any-return]  # NOQA: E501            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^   File "C:\Users\ASUS\Desktop\云计算\facial-recognition-attendance\.venv\Lib\site-packages\pymysql\connections.py", line 365, in __init__     self.connect()   File "C:\Users\ASUS\Desktop\云计算\facial-recognition-attendance\.venv\Lib\site-packages\pymysql\connections.py", line 681, in connect     self._request_authentication()   File "C:\Users\ASUS\Desktop\云计算\facial-recognition-attendance\.venv\Lib\site-packages\pymysql\connections.py", line 980, in _request_authentication     auth_packet = _auth.caching_sha2_password_auth(self, auth_packet)                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^   File "C:\Users\ASUS\Desktop\云计算\facial-recognition-attendance\.venv\Lib\site-packages\pymysql\_auth.py", line 272, in caching_sha2_password_auth     pkt = _roundtrip(conn, data)           ^^^^^^^^^^^^^^^^^^^^^^   File "C:\Users\ASUS\Desktop\云计算\facial-recognition-attendance\.venv\Lib\site-packages\pymysql\_auth.py", line 121, in _roundtrip     pkt = conn._read_packet()           ^^^^^^^^^^^^^^^^^^^   File "C:\Users\ASUS\Desktop\云计算\facial-recognition-attendance\.venv\Lib\site-packages\pymysql\connections.py", line 782, in _read_packet     packet.raise_for_error()   File "C:\Users\ASUS\Desktop\云计算\facial-recognition-attendance\.venv\Lib\site-packages\pymysql\protocol.py", line 219, in raise_for_error     err.raise_mysql_exception(self._data)   File "C:\Users\ASUS\Desktop\云计算\facial-recognition-attendance\.venv\Lib\site-packages\pymysql\err.py", line 150, in raise_mysql_exception     raise errorclass(errno, errval) pymysql.err.OperationalError: (1045, "Access denied for user 'face_user'@'localhost' (using password: YES)")
The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\ASUS\Desktop\云计算\facial-recognition-attendance\.venv\Lib\site-packages\starlette\routing.py", line 677, in lifespan
    async with self.lifespan_context(app) as maybe_state:
  File "C:\Users\ASUS\AppData\Local\Programs\Python\Python312\Lib\contextlib.py", line 210, in __aenter__
    return await anext(self.gen)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ASUS\Desktop\云计算\facial-recognition-attendance\backend\main.py", line 31, in lifespan
    init_db()
  File "C:\Users\ASUS\Desktop\云计算\facial-recognition-attendance\backend\utils\database.py", line 42, in init_db
    UserBase.metadata.create_all(bind=engine)
  File "C:\Users\ASUS\Desktop\云计算\facial-recognition-attendance\.venv\Lib\site-packages\sqlalchemy\sql\schema.py", line 5930, in create_all
    bind._run_ddl_visitor(
  File "C:\Users\ASUS\Desktop\云计算\facial-recognition-attendance\.venv\Lib\site-packages\sqlalchemy\engine\base.py", line 3269, in _run_ddl_visitor
    with self.begin() as conn:
  File "C:\Users\ASUS\AppData\Local\Programs\Python\Python312\Lib\contextlib.py", line 137, in __enter__
    return next(self.gen)
           ^^^^^^^^^^^^^^
  File "C:\Users\ASUS\Desktop\云计算\facial-recognition-attendance\.venv\Lib\site-packages\sqlalchemy\engine\base.py", line 3259, in begin
    with self.connect() as conn:
         ^^^^^^^^^^^^^^
  File "C:\Users\ASUS\Desktop\云计算\facial-recognition-attendance\.venv\Lib\site-packages\sqlalchemy\engine\base.py", line 3295, in connect
    return self._connection_cls(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ASUS\Desktop\云计算\facial-recognition-attendance\.venv\Lib\site-packages\sqlalchemy\engine\base.py", line 146, in __init__
    Connection._handle_dbapi_exception_noconnection(
  File "C:\Users\ASUS\Desktop\云计算\facial-recognition-attendance\.venv\Lib\site-packages\sqlalchemy\engine\base.py", line 2450, in _handle_dbapi_exception_noconnection
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "C:\Users\ASUS\Desktop\云计算\facial-recognition-attendance\.venv\Lib\site-packages\sqlalchemy\engine\base.py", line 144, in __init__
    self._dbapi_connection = engine.raw_connection()
                             ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ASUS\Desktop\云计算\facial-recognition-attendance\.venv\Lib\site-packages\sqlalchemy\engine\base.py", line 3319, in raw_connection
    return self.pool.connect()
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ASUS\Desktop\云计算\facial-recognition-attendance\.venv\Lib\site-packages\sqlalchemy\pool\base.py", line 448, in connect
    return _ConnectionFairy._checkout(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ASUS\Desktop\云计算\facial-recognition-attendance\.venv\Lib\site-packages\sqlalchemy\pool\base.py", line 1272, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ASUS\Desktop\云计算\facial-recognition-attendance\.venv\Lib\site-packages\sqlalchemy\pool\base.py", line 712, in checkout
    rec = pool._do_get()
          ^^^^^^^^^^^^^^
  File "C:\Users\ASUS\Desktop\云计算\facial-recognition-attendance\.venv\Lib\site-packages\sqlalchemy\pool\impl.py", line 178, in _do_get
    with util.safe_reraise():
  File "C:\Users\ASUS\Desktop\云计算\facial-recognition-attendance\.venv\Lib\site-packages\sqlalchemy\util\langhelpers.py", line 122, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "C:\Users\ASUS\Desktop\云计算\facial-recognition-attendance\.venv\Lib\site-packages\sqlalchemy\pool\impl.py", line 176, in _do_get
    return self._create_connection()
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ASUS\Desktop\云计算\facial-recognition-attendance\.venv\Lib\site-packages\sqlalchemy\pool\base.py", line 389, in _create_connection
    return _ConnectionRecord(self)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ASUS\Desktop\云计算\facial-recognition-attendance\.venv\Lib\site-packages\sqlalchemy\pool\base.py", line 674, in __init__
    self.__connect()
  File "C:\Users\ASUS\Desktop\云计算\facial-recognition-attendance\.venv\Lib\site-packages\sqlalchemy\pool\base.py", line 900, in __connect
    with util.safe_reraise():
  File "C:\Users\ASUS\Desktop\云计算\facial-recognition-attendance\.venv\Lib\site-packages\sqlalchemy\util\langhelpers.py", line 122, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "C:\Users\ASUS\Desktop\云计算\facial-recognition-attendance\.venv\Lib\site-packages\sqlalchemy\pool\base.py", line 896, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ASUS\Desktop\云计算\facial-recognition-attendance\.venv\Lib\site-packages\sqlalchemy\engine\create.py", line 667, in connect
    return dialect.connect(*cargs_tup, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ASUS\Desktop\云计算\facial-recognition-attendance\.venv\Lib\site-packages\sqlalchemy\engine\default.py", line 630, in connect
    return self.loaded_dbapi.connect(*cargs, **cparams)  # type: ignore[no-any-return]  # NOQA: E501
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ASUS\Desktop\云计算\facial-recognition-attendance\.venv\Lib\site-packages\pymysql\connections.py", line 365, in __init__
    self.connect()
  File "C:\Users\ASUS\Desktop\云计算\facial-recognition-attendance\.venv\Lib\site-packages\pymysql\connections.py", line 681, in connect
    self._request_authentication()
  File "C:\Users\ASUS\Desktop\云计算\facial-recognition-attendance\.venv\Lib\site-packages\pymysql\connections.py", line 980, in _request_authentication
    auth_packet = _auth.caching_sha2_password_auth(self, auth_packet)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ASUS\Desktop\云计算\facial-recognition-attendance\.venv\Lib\site-packages\pymysql\_auth.py", line 272, in caching_sha2_password_auth
    pkt = _roundtrip(conn, data)
          ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ASUS\Desktop\云计算\facial-recognition-attendance\.venv\Lib\site-packages\pymysql\_auth.py", line 121, in _roundtrip
    pkt = conn._read_packet()
          ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ASUS\Desktop\云计算\facial-recognition-attendance\.venv\Lib\site-packages\pymysql\connections.py", line 782, in _read_packet
    packet.raise_for_error()
  File "C:\Users\ASUS\Desktop\云计算\facial-recognition-attendance\.venv\Lib\site-packages\pymysql\protocol.py", line 219, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "C:\Users\ASUS\Desktop\云计算\facial-recognition-attendance\.venv\Lib\site-packages\pymysql\err.py", line 150, in raise_mysql_exception
    raise errorclass(errno, errval)
sqlalchemy.exc.OperationalError: (pymysql.err.OperationalError) (1045, "Access denied for user 'face_user'@'localhost' (using password: YES)")
(Background on this error at: https://sqlalche.me/e/20/e3q8)

ERROR:    Application startup failed. Exiting.

进程已结束，退出代码为 3